In [2]:
print("Hello Python Welcome to the Numpy Learning")

Hello Python Welcome to the Numpy Learning


In [9]:
import numpy as np

#### Basic Array Creation

In [10]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [11]:
arr = np.array([1,2,3,4,4.5,"Hello"])
arr # this array data type will be changes to string as an array should have only one type of data.

array(['1', '2', '3', '4', '4.5', 'Hello'], dtype='<U32')

In [12]:
# Now we will learn about the Vectors and Multi Dimensional Array

# --- Vector --- 
    # It is a one dimensional array it means there will be only one row for ex :- np.array([1,2,3,4,5])

# --- Multi Dimensional Array
    # In the multi dimensional array there will be multiple rows and multiple coloumns which looks like a Matrix. There are so many dimensional arrays like 2-D Array, 3-D Array etc...

In [13]:
l = [[1,2,3,4],[1,2,3,4],[1,2,3,4]]
l

[[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]

In [14]:
np.array(l)

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

#### Array Generation Function

In [16]:
np.arange(1,20,2) # it is similar like a range function we have to pass (start,stop,step)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [17]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [19]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
arr = np.linspace(0,1,3) # It is a very important function which means - It return evenly spaced numbers over a specified interval. In function we will pass (start, stop ,end) 
arr 

array([0. , 0.5, 1. ])

In [27]:
arr = np.linspace(0,2,20)
arr

array([0.        , 0.10526316, 0.21052632, 0.31578947, 0.42105263,
       0.52631579, 0.63157895, 0.73684211, 0.84210526, 0.94736842,
       1.05263158, 1.15789474, 1.26315789, 1.36842105, 1.47368421,
       1.57894737, 1.68421053, 1.78947368, 1.89473684, 2.        ])

#### Random Generation Function

In [30]:
np.random.rand(5) # This function only generates random numbers btw 0 to 1 so this is a concept of Normilization

array([0.72946188, 0.55487933, 0.72859928, 0.79013986, 0.54332319])

In [41]:
np.random.randn(5) # This function only generates random numbers btw -3 to 3 so this is a concept of Standardization

array([ 0.89274953,  0.14863737,  0.03626619, -0.10275363, -0.55382941])

In [44]:
np.random.randint(5,20,10) # This is a function where random integer number are generated randomly and in this array we will pass three arguments (Start No. , End No. , Number of Numbers you want to generate btw start and end)

array([14,  7, 19, 15, 15,  6, 14,  5, 11,  5], dtype=int32)

#### Array Attributes

In [46]:
# We already know what are attributes now there are some attributes in numpy let's see them and when we call that attribute we don't need to call that attributes with ()

In [51]:
arr = np.array([[1,2,23,34,4],[12,3,3,2,34],[23,34,5,34,36]])
arr

array([[ 1,  2, 23, 34,  4],
       [12,  3,  3,  2, 34],
       [23, 34,  5, 34, 36]])

In [52]:
arr.shape

(3, 5)

In [53]:
arr.size

15

In [55]:
arr.dtype

dtype('int64')

#### Array Methods

In [58]:
arr

array([[ 1,  2, 23, 34,  4],
       [12,  3,  3,  2, 34],
       [23, 34,  5, 34, 36]])

In [59]:
arr.min()

np.int64(1)

In [60]:
arr.max()

np.int64(36)

In [61]:
arr.sum()

np.int64(250)

In [63]:
np.sum(arr,axis=1) # In this method the axis will tell to sum which numbers like if you give 1 then it will sum row wise so (1 - is for row wise) and (2- is for column wise)

array([ 64,  54, 132])

In [64]:
arr.mean()

np.float64(16.666666666666668)

In [65]:
arr.std()

np.float64(14.197026292697903)

#### Reshaping and Resizing

In [73]:
arr = np.arange(0,20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [75]:
arr.reshape(4,5) # This will reshape the array dimensions and size. 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])