In [1]:
import numpy as np

#### Numpy Indexing and Slicing of vectors

In [4]:
arr = np.random.randint(0,10,10)
arr

array([9, 6, 6, 4, 8, 1, 3, 9, 3, 3], dtype=int32)

In [6]:
arr[1:4:1] # Array slicing is also same like a list, we are gonna pass for slicing the array are [start idx, end idx, steps]

array([6, 6, 4], dtype=int32)

#### Numpy Indexing and Slicing of Multi Dimensional 

In [ ]:
# In above we saw how the Indexing and Slicing works in vectors but now we will see how it will work in 2-D

In [13]:
arr = np.random.randint(6,30,20).reshape(4,5)
arr

array([[18, 18, 24, 10,  9],
       [18, 17, 15,  8,  8],
       [24, 24, 25, 24, 12],
       [20,  6, 22, 22, 16]], dtype=int32)

In [16]:
arr[3] # this will give the whole row of the matrix. to access single element we gonna pass both row and column index

array([20,  6, 22, 22, 16], dtype=int32)

In [23]:
arr[1,1] # see in this we passes 1,1 which means first 1 is the second row and second 1 is second column so the number is 17 

np.int32(17)

In [24]:
arr[2,4]

np.int32(12)

In [25]:
# Now we will se how slicing works in 2D Array

In [33]:
arr = np.arange(0,15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [41]:
arr[0:2,1:4] # When we perform slicing for 2D array we have to pass both row and column index for slicing for ex - [Row-Start-Idx:End-Idx , Column-Start:End-Idx]

array([[1, 2, 3],
       [6, 7, 8]])

In [45]:
arr[:2,:]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [49]:
arr[:,3] # This will give whole column 

array([ 3,  8, 13])

#### Boolean Indexing

In [56]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
bool_idx = arr % 2  == 0
bool_idx

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [60]:
arr = arr[bool_idx]
arr

array([0, 2, 4, 6, 8])