## ARRAY OPERATIONS

#### Arithmetic Operations

In [3]:
import numpy as np

In [4]:
# We perform arithmetic operations like +,-,*,/ etc... with two arrays

In [5]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [7]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [9]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [10]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [11]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [12]:
a1 // a2

array([0, 0, 0, 0, 0])

#### Broadcasting 

In [15]:
l = [1,2,3,4,5]
arr = np.array(l)
l
print(type(l))

<class 'list'>


In [16]:
# If you want to multiple 10 to each element of the list then you have to run a loop. But in Array we use broadcast to perform any operations to the array

In [18]:
arr * 10 # This is Broadcasting

array([10, 20, 30, 40, 50])

In [19]:
# We can do Broadcasting on 2D matrix also let's see with an example

In [22]:
mt = np.arange(1,21).reshape(4,5)
mt

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [23]:
mt * 10

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200]])

In [24]:
mt + 20

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

#### Deep Copy and Shallow Copy 

In [25]:
# Shallow Copy - Makes a copy but inner parts are still connected to the original

In [26]:
# Deep Copy - Makes a complete separate copy that won't affect the original

In [42]:
ori = np.array([1,2,3,4,5,6])
ori

array([1, 2, 3, 4, 5, 6])

In [47]:
slic = ori[:3]
slic[0] = 10
slic

array([10,  2,  3])

In [49]:
ori # Here we can se that when we slice from an ori array and do any changes in the sliced array then the changes will affect the original array. So, here the shallow copy is done as the inner parts are connected to the original

array([10,  2,  3,  4,  5,  6])

In [50]:
deep = ori.copy()
deep

array([10,  2,  3,  4,  5,  6])

In [52]:
deep[1] = 20
deep

array([10, 20,  3,  4,  5,  6])

In [54]:
ori # Here we can see that the deep copy method is used. In deep copy a separate copy is created in the RAM both original and copied array are at different location that's why when changes are done at one array do not refelect other's

array([10,  2,  3,  4,  5,  6])

#### Matric Operations

In [60]:
mt1 = np.arange(1,5).reshape(2,2)
mt2 = np.arange(5,9).reshape(2,2)

In [61]:
mt1 + mt2

array([[ 6,  8],
       [10, 12]])

In [63]:
mt1 * mt2  # This multiplies the matrix by index means, it doesn't uses matrix multiplication. To do multiplication using matric multiplication we use @ 

array([[ 5, 12],
       [21, 32]])

In [64]:
 mt1 @ mt2

array([[19, 22],
       [43, 50]])

In [67]:
mt1.dot(mt2) # The matrix multiplication is also known as a dot product so, there is function called dot 

array([[19, 22],
       [43, 50]])

In [68]:
# Transpose Matrix

In [71]:
mt1.T # Transpose the matrix mt1 (swap rows and columns)

array([[1, 3],
       [2, 4]])

#### Advance Array Manipulation 

##### Stacking Array

In [72]:
# Stacking array - Means the joining and combining of multiple arrays to form a larger array. We cant stack the matrix array

In [78]:
a = np.arange(6)
b = np.arange(6)

In [82]:
np.vstack((a,b)) # Join Vertically 

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [83]:
np.hstack((a,b)) # Join Horizontally

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])

In [84]:
np.column_stack((a,b))

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5]])

##### Splitting Array

In [88]:
ab = np.arange(16).reshape(4,4)
ab

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [90]:
np.hsplit(ab,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [92]:
np.vsplit(ab,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]