In [1]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])


In [4]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [9]:
#Find the average age of students.
data.mean()

np.float64(61.06666666666667)

In [10]:
#Extract Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [16]:
#Find the highest Science mark.
sci = data[:,2]
sci.max()

np.int64(95)

In [22]:
#Get details of the student who scored more than 90 in Math.
math = data[:,1]
ans = math > 90 
result = data[ans]
result

array([[19, 92, 88]])

In [24]:
#Increase Math marks of all students by 5.
math + 5

array([90, 97, 81, 70, 95])

In [28]:
#Find how many students are younger than 19.
age = data[:,0]
filter_age = age < 19 
age = age[filter_age]
age

array([18, 17, 18])

In [32]:
#Calculate the average marks in each subject (column-wise mean).
math = data[:,1]
scii = data[:,2]
print(math.mean())
print(scii.mean())

81.6
83.2


In [36]:
#Get data of students who scored at least 80 in both subjects.
anss = (math >= 80 ) & (scii >= 80)
resultsss = data[anss]
resultsss

array([[19, 92, 88],
       [20, 90, 85]])

In [39]:
#Replace all Science marks < 75 with 0.
a = scii < 75
data[a,2] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])

#### Valid Sudoku

In [40]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [44]:
a = np.sum(s,1)
for i in a:
    if(i != 45):
        print("Your suduko is not valid")
        break
else:
    print('The sum of row wise are equal')

The sum of row wise are equal


In [45]:
a = np.sum(s,0)
for i in a:
    if(i != 45):
        print("Your suduko is not valid")
        break
else:
    print('The sum of column wise are equal')

The sum of column wise are equal


In [53]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3, j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45
